### ISSUE TITLE
Where can I Download the test data?

### ISSUE THREAD

**Issue by ricky-696** [salmank255/Road-waymo-dataset#2]
Hello, I saw that the Test data release is scheduled for July 15, 2023 at [HERE](https://sites.google.com/view/road-plus-plus/challenge?authuser=0#h.4c1z66l3tne2). 
Where can I find the download link or directly provide the link to us.

Thanks for help!

**Comment by salmank255** [comment]
Hi @ricky-696,

We are extending the release dates due to some issues and will release the test data soon.

**Comment by JiaweiZhao-git** [comment]
Will the submission deadline be delayed？

**Comment by salmank255** [comment]
Hi @JiaweiZhao-git,

Yes, we will extend the submission deadlines. Sorry for the delay in releasing the test set.

**Comment by salmank255** [comment]
Hi @JiaweiZhao-git and @ricky-696,

The test-set of our ROAD++ challenge is released and can be downloaded from the community contribution section of the Waymo open dataset following this link: https://waymo.com/open/download/ If you have any questions, please let us know.

**Comment by JiaweiZhao-git** [comment]
@salmank255 I didn't find the **road_waymo_test_v1.0.json** in this link, where could I download it?

**Comment by salmank255** [comment]
@JiaweiZhao-git It's a test ground truth file we don't provide it. You need to generate your prediction based on the guidelines provided in our eval.ai challenge page (https://eval.ai/web/challenges/challenge-page/2043/evaluation)
