### ISSUE TITLE
Submit format question

### ISSUE THREAD

**Issue by ricky-696** [salmank255/Road-waymo-dataset#4]
Hello, I would like to confirm the format for the final submission. The tubes data is as follows:
```
tubes = {
    # For the agent detection phase
    'agent': {
        # For each video
        'train_00601': [
            # For each tube
            # tube 1
            {   # class index
                'label_id': 0,
                # bounding box scores
                'scores': [0.11491841, 0.16743928, 0.16620131, 0.25436875, 0.3424321, 0.13464102],
                # bounding box coordinates (absolute)
                'boxes': [[473.2007, 229.3157, 485.1342, 255.87836],
                          [475.29144, 229.99019, 487.3297, 256.3758],
                          [476.7905, 231.2161, 488.5682, 256.20172],
                          [476.16983, 232.67128, 487.9435, 256.62274],
                          [477.0421, 233.207, 489.6095, 261.4667],
                          [476.92032, 231.34416, 489.44467, 258.55612]],
                # tube score
                'score': 0.2984004318714142,
                # frames across which the tube spans
                'frames': [3, 4, 5, 6, 7, 8]
            },
```
1. I would like to ask about the data structure of `scores`, `boxes`, and `frames`. Are they Python **lists** or **ndarrays**?
(I reviewed the [tube_helper.py](https://github.com/salmank255/ROAD_Waymo_Baseline/blob/1f785a09a54522a042bf45de8bdaa10d2eb15430/modules/tube_helper.py#L40) and I believe the data structures should be **ndarrays**, but I would like to double-check. Thank you for your assistance.)

2. Is the Type(tubes['agent']['train_00601']) == list ?

3. Is the final submission to EvalAI just packaging the 'tube' dictionary into a .pkl file?

Thanks for help!

**Comment by salmank255** [comment]
Hi @ricky-696,

Response to your queries are:

1. **ndarrays**, as we are using the same tube_helper function.
2. yes list of dictionaries (tubes)
3. yes we are expecting the same structure to validation set.

If you have any further queries please let me know.

**Comment by ricky-696** [comment]
Hello, sorry to bother you again. I used the format mentioned above to submit my results on EvalAI, and I encountered the following Traceback:
```
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 504, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmpf7992pl3/compute/challenge_data/challenge_2043/main.py", line 186, in evaluate
    iou_thresh=0.1)
  File "/tmp/tmpf7992pl3/compute/challenge_data/challenge_2043/road_eval.py", line 259, in evaluate_tubes
    class_ap, num_postives, count, recall = compute_class_ap(class_dets, class_gts, get_tube_3Diou, iou_thresh, metric_type=metric_type)
  File "/tmp/tmpf7992pl3/compute/challenge_data/challenge_2043/road_eval.py", line 201, in compute_class_ap
    for gt in class_gts[iid]])
  File "/tmp/tmpf7992pl3/compute/challenge_data/challenge_2043/road_eval.py", line 201, in <listcomp>
    for gt in class_gts[iid]])
  File "/tmp/tmpf7992pl3/compute/challenge_data/challenge_2043/modules/tube_helper.py", line 297, in get_tube_3Diou
    siou = iou3d(tube_a_boxes, tube_b_boxes)
  File "/tmp/tmpf7992pl3/compute/challenge_data/challenge_2043/modules/tube_helper.py", line 329, in iou3d
    assert tube_a.shape[0] == tube_b.shape[0]
AssertionError
```

After inspecting the `modules/tube_helper.py`, I identified the cause of this issue:

In the [code](https://github.com/salmank255/ROAD_Waymo_Baseline/blob/65049d6e633c90cb5924b36a4c74f69e5551d491/modules/tube_helper.py#L294), `get_tube_3Diou` function only handles cases where 
`if tube_a_boxes.shape[0] > tube_b_boxes.shape[0]`
(the number of **predict boxes** is greater than the number of **ground truth boxes**), 

but it doesn't handle cases where 
`if tube_a_boxes.shape[0] < tube_b_boxes.shape[0]` 
(the number of **predict boxes** is less than the number of **ground truth boxes**). 

As a result, the error occurs when the function `iou3d(tube_a_boxes, tube_b_boxes)` is called, specifically due to the assertion `assert tube_a.shape[0] == tube_b.shape[0]`. If my understanding is incorrect, please correct me. 

Thanks for help!

**Comment by ricky-696** [comment]
Hello @salmank255, 
Please let me know if my understanding of `tube_helper.py` is correct or incorrect, as all the current submissions are encountering this traceback.

Thanks for help!

**Comment by salmank255** [comment]
Hi @ricky-696,

Sorry for the delay in response, yes you are right could you please provide your prediction file pkl or zip, I will try it locally and get back to you about the exact error or if there's any bug will try to fix it soon. 

Is "CCU_MVL" your team name, if yes, I will simply download your prediction from the eval.ai

**Comment by ricky-696** [comment]
Hi @salmank255,
Yes, we are "CCU_MVL." 
We have submitted two pkl files. If there are any format errors, please let us know.

Thanks for help!

**Comment by salmank255** [comment]
I will try tomorrow and get back to you then

**Comment by xingexjj** [comment]
> Hi @ricky-696,
> 
> Sorry for the delay in response, yes you are right could you please provide your prediction file pkl or zip, I will try it locally and get back to you about the exact error or if there's any bug will try to fix it soon.
> 
> Is "CCU_MVL" your team name, if yes, I will simply download your prediction from the eval.ai

Hello @salmank255 
Could you please test my submission file locally as well? My submission file has been stayed at 'running' state so I don't know the exact error. I can evaluate my prediction file on validation set on my own computer, but I can't get the result from eval.ai.

**Comment by salmank255** [comment]
Hi @xingexjj,

I can't see any submission by your team (CCU_MVL) which is running. Some of them are there but it got failed. Can you please resubmit then I will try to see what the problem is or evaluate on my local

**Comment by ricky-696** [comment]
> I will try tomorrow and get back to you then

Hi @salmank255 
Is the bug fixed or our submission format are wrong?
here is our file's [link](https://evalai.s3.amazonaws.com/media/submission_files/submission_297911/f122cbf8-fcbc-403c-a65f-e68a3aefe5fa.zip)

**Comment by xingexjj** [comment]
> Hi @xingexjj,
> 
> I can't see any submission by your team (CCU_MVL) which is running. Some of them are there but it got failed. Can you please resubmit then I will try to see what the problem is or evaluate on my local

Sorry but my team's name is leno. Could you please check if my team's submissions are running?

**Comment by salmank255** [comment]
> > Hi @xingexjj,
> > I can't see any submission by your team (CCU_MVL) which is running. Some of them are there but it got failed. Can you please resubmit then I will try to see what the problem is or evaluate on my local
> 
> Sorry but my team's name is leno. Could you please check if my team's submissions are running?

I can see your submissions it's running for the validation set but it's completed for the test set.

**Comment by xingexjj** [comment]
> > > Hi @xingexjj,
> > > I can't see any submission by your team (CCU_MVL) which is running. Some of them are there but it got failed. Can you please resubmit then I will try to see what the problem is or evaluate on my local
> > 
> > 
> > Sorry but my team's name is leno. Could you please check if my team's submissions are running?
> 
> I can see your submissions it's running for the validation set but it's completed for the test set.

That's because I haven't used my newest method on the test set. I just got the result on the validation set first.

**Comment by salmank255** [comment]
> > I will try tomorrow and get back to you then
> 
> Hi @salmank255 Is the bug fixed or our submission format are wrong? here is our file's [link](https://evalai.s3.amazonaws.com/media/submission_files/submission_297911/f122cbf8-fcbc-403c-a65f-e68a3aefe5fa.zip)

You provided submission file is having assertion error I think your predictions are not for full data

**Comment by salmank255** [comment]
> > > > Hi @xingexjj,
> > > > I can't see any submission by your team (CCU_MVL) which is running. Some of them are there but it got failed. Can you please resubmit then I will try to see what the problem is or evaluate on my local
> > > 
> > > 
> > > Sorry but my team's name is leno. Could you please check if my team's submissions are running?
> > 
> > 
> > I can see your submissions it's running for the validation set but it's completed for the test set.
> 
> That's because I haven't used my newest method on the test set. I just got the result on the validation set first.

Below are the results for agent detection on validation set, I think the server is busy and having issues with some files. I will requst for the upgradation and update your here.

{'result': [{'val_split': {'Agent@0.1': 11.991370127070695, 'Agent@0.2': 8.01788265700452, 'Agent@0.5': 3.4292073079996044, 'Average': 7.812820030691607}}]}

**Comment by xingexjj** [comment]
@salmank255 Thank you for helping me. Wish you can handle the issues soon.

**Comment by ricky-696** [comment]
> > > I will try tomorrow and get back to you then
> > 
> > 
> > Hi @salmank255 Is the bug fixed or our submission format are wrong? here is our file's [link](https://evalai.s3.amazonaws.com/media/submission_files/submission_297911/f122cbf8-fcbc-403c-a65f-e68a3aefe5fa.zip)
> 
> You provided submission file is having assertion error I think your predictions are not for full data

Hi, @salmank255

This assertion occurs when there are missing frames in tube_a(predict boxes) within a continuous sequence.
For example: 
`tube_a['frames'] = [3, 4, 6, 7, 8]` but `tube_b['frames'] = [3, 4, 5, 6, 7, 8]` (5th frame is missing)

Our participating team can resolve this issue by bbox's linear interpolation. However, I believe that appropriate measures (such as zero padding) should be taken in the [evaluation code](https://github.com/salmank255/ROAD_Waymo_Baseline/blob/65049d6e633c90cb5924b36a4c74f69e5551d491/modules/tube_helper.py#L288) for such cases, as the model might encounter missed detections when objects are occluded.


If you want to reproduce this assertion, you can use the following code:
```
import numpy as np
from modules.tube_helper import get_tube_3Diou

if __name__ == '__main__':
    tube_a = {
                'label_id': 0,
                'scores': np.array([0.11491841, 0.16743928, 0.25436875, 0.3424321, 0.13464102]),
                'boxes': np.array([[473.2007, 229.3157, 485.1342, 255.87836],
                                   [475.29144, 229.99019, 487.3297, 256.3758],
                                   [476.16983, 232.67128, 487.9435, 256.62274],
                                   [477.0421, 233.207, 489.6095, 261.4667],
                                   [476.92032, 231.34416, 489.44467, 258.55612]]),
                'score': 0.2984004318714142,
                'frames': np.array([3, 4, 6, 7, 8])
            }
    
    tube_b = {  
                'label_id': 0,
                'scores': np.array([0.11491841, 0.16743928, 0.16620131, 0.25436875, 0.3424321, 0.13464102]),
                'boxes': np.array([[473.2007, 229.3157, 485.1342, 255.87836],
                                   [475.29144, 229.99019, 487.3297, 256.3758],
                                   [476.7905, 231.2161, 488.5682, 256.20172],
                                   [476.16983, 232.67128, 487.9435, 256.62274],
                                   [477.0421, 233.207, 489.6095, 261.4667],
                                   [476.92032, 231.34416, 489.44467, 258.55612]]),
                'score': 0.2984004318714142,
                'frames': np.array([3, 4, 5, 6, 7, 8])
            }
    
    get_tube_3Diou(tube_a, tube_b)
```

Thanks for help!

**Comment by salmank255** [comment]
Hi @ricky-696,

I am glad the problem is resolved and many thanks for providing the code we will try our best to resolve such inconsistencies in our code.

**Comment by ricky-696** [comment]
> > > > > Hi @xingexjj,
> > > > > I can't see any submission by your team (CCU_MVL) which is running. Some of them are there but it got failed. Can you please resubmit then I will try to see what the problem is or evaluate on my local
> > > > 
> > > > 
> > > > Sorry but my team's name is leno. Could you please check if my team's submissions are running?
> > > 
> > > 
> > > I can see your submissions it's running for the validation set but it's completed for the test set.
> > 
> > 
> > That's because I haven't used my newest method on the test set. I just got the result on the validation set first.
> 
> Below are the results for agent detection on validation set, I think the server is busy and having issues with some files. I will requst for the upgradation and update your here.
> 
> {'result': [{'val_split': {'Agent@0.1': 11.991370127070695, 'Agent@0.2': 8.01788265700452, 'Agent@0.5': 3.4292073079996044, 'Average': 7.812820030691607}}]}

Hi @salmank255 
Is the agent detection's test set correct now? I got the results below:
`{"test_split": {"Agent@0.1": 0.0, "Agent@0.2": 0.0, "Agent@0.5": 0.0, "Average": 0.0}}`
